POST  http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"João",
    "lastName": "Santos",
    "participation":"50"
}

###
GET http://localhost:3003/user/search?name=Regiscleia

